# A name and description for your site.
name:         Poly
description:  A simple way to manage your content.

# The URL the site will live at. 
url: http://your-site.com

# Who writes here?
author: Author of Site

# Which theme do you want to use?
theme: base

# Do you have a google analytics ID? If so, paste it here.
google_analytics: UA-XXXXX-X

# An array of emails who can login and 
# edit content in this app.
authorized_emails:
  - me@briangonzalez.org

# Persona, Mozilla's login platform, must know
# which URL your site will live at.
audience: http://*.your-site.com